
services:
  app:
    build: .
    container_name: egispatin_app
    working_dir: /var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www/html
      - ./docker/overrides/storage/framework/views:/var/www/html/storage/framework/views
    ports:
      - "9080:9000"
    depends_on:
      - mysql
    networks:
      - egispatin

  node:
    image: node:22
    container_name: node_egispatin
    working_dir: /var/www/html
    user: "${UID:-1000}:${GID:-1000}"
    volumes:
      - ./:/var/www/html
    ports:
      - "5173:5173"
    networks:
      - egispatin
    command: tail -f /dev/null  # biar container node tetap hidup dan bisa exec manual

  webserver:
    image: nginx:alpine
    container_name: nginx_egispatin
    restart: unless-stopped
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - egispatin

  mysql:
    image: mysql:8.0
    container_name: mysql_egispatin
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: e-gispatin
      MYSQL_USER: e-gispatin
      MYSQL_PASSWORD: e-gispatin
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - egispatin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_egispatin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql_egispatin   # Sesuai nama service MySQL
      PMA_PORT: 3306
    depends_on:
      - mysql
    networks:
      - egispatin

networks:
  egispatin:

volumes:
  mysql_data: